{
 "title": "Keycloak & Traefik",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Average requests duration since metrics are recorded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "traefik_service_request_duration_seconds_sum/traefik_service_request_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request duration per interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(traefik_service_request_duration_seconds_sum{code=\"200\"}[$__rate_interval]) / increase(traefik_service_request_duration_seconds_count{code=\"200\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Keycloak sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "vendor_statistics_approximate_entries_unique{cache=\"sessions\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}